### ISSUE TITLE
勘误参考？

### ISSUE THREAD

**Issue by yaowenxu** [LiuXiaoxuanPKU/Cost-Model-papers#1]
Hi，我看了你的论文，写得很好，提供了新的角度；

我发现其中有两个笔误：
其中对15的公式的分母和分子的解释，是不是写反了；alpha的差值表示MOM内存节约程度，应该是指分子numerator？
公式17下面一段里的 H，是不是应该是W？

然后有个问题，想请教一下：
在真实使用中，如何来获取并计算这个 PAPAYA Score呢，是先通过 profiling，进行拟合，求得对应参数吗？

谢谢！

**Comment by LiuXiaoxuanPKU** [comment]
Hi, thanks for the attention!!

(1) yes you are right, it's numerator and it should be W.
(2) yes, you need to profile first to fit the parameters. But since batch latency and memory are all linear, we imagine the profiling time should not take that long. (only profile a few data points to get a good prediction)

Please let me know if you meet more problems, thanks a lot!
